# Generated by Django 4.1.4 on 2022-12-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_policies', '0003_alter_passwordrecord_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordrecord',
            options={'get_latest_by': 'date'},
        ),
    ]
